---
- name: 'Clone the nzbToMedia scripts to /opt/nzbtomedia'
  git:
    repo: 'https://github.com/clinton-hall/nzbToMedia.git'
    dest: '/opt/nzbtomedia'
    version: '3e4861e87c543a4d2debd8997feb16bda3ef5339'

- name: 'Start the sabnzbd docker container'
  docker:
    image: "linuxserver/sabnzbd"
    name: "{{ docker_sabnzbd_container_name }}"
    env:
      PUID: '0'
      PGID: '0'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ docker_sabnzbd_mounted_directory }}/config:/config'
      - '{{ docker_sabnzbd_mounted_directory }}/downloads:/downloads'
      - '{{ docker_sabnzbd_mounted_directory }}/incomplete-downloads:/incomplete-downloads'
      - '/opt/nzbtomedia:/nzbtomedia'
    ports: '{{ docker_sabnzbd_exposed_port }}:8080'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ docker_sabnzbd_container_name }}"
