---
- name: 'Start the sabnzbd docker container'
  docker:
    image: "linuxserver/sabnzbd"
    name: "{{ docker_sabnzbd_container_name }}"
    env:
      PUID: '0'
      PGID: '0'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ docker_sabnzbd_mounted_directory }}/config:/config'
      - '{{ docker_sabnzbd_mounted_directory }}/downloads:/downloads'
      - '{{ docker_sabnzbd_mounted_directory }}/incomplete-downloads:/incomplete-downloads'
    ports: '{{ docker_sabnzbd_exposed_port }}:8080'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ docker_sabnzbd_container_name }}"
