---
- name: 'docker_sabnzbd-restart-docker-sabnzbd'
  docker:
    image: "timhaak/sabnzbd"
    name: "{{ docker_sabnzbd_container_name }}"
    volumes:
      - "{{ docker_sabnzbd_config_directory }}/sabnzbd.ini:/config/sabnzbd.ini"
      - "{{ docker_sabnzbd_data_directory }}:/data"
    ports: '8080:8080'
    state: 'stopped'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ docker_sabnzbd_container_name }}"
  notify: 'docker_sabnzbd-start-docker-sabnzbd'

- name: 'docker_sabnzbd-start-docker-sabnzbd'
  docker:
    image: "timhaak/sabnzbd"
    name: "{{ docker_sabnzbd_container_name }}"
    volumes:
      - "{{ docker_sabnzbd_config_directory }}/sabnzbd.ini:/config/sabnzbd.ini"
      - "{{ docker_sabnzbd_data_directory }}:/data"
    ports: '8080:8080'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ docker_sabnzbd_container_name }}"
